In [11]:
import pandas as pd
import numpy as np

In [185]:
df_2022 = pd.read_csv("data/kaggle_survey_2022_responses.csv")

/var/folders/6v/12r4qnjx54zgmfy66mv7j0rr0000gn/T/ipykernel_28764/1897696131.py:1: DtypeWarning: Columns (0,208,225,255,257,260,270,271,277) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv("kaggle_survey_2022_responses.csv")

In [186]:
data_dict_2022 = df_2022.loc[0,:].to_dict()

In [187]:
def extract_mcq_questions(data_dict, q_string, descriptor_string):
    q_keys = list(filter(lambda x: q_string in x, list(data_dict.keys())))
    mcq_dict = {}
    for q_key in q_keys:
        mcq_dict[q_key] = descriptor_string + re.search('Selected Choice - (.+?)$', data_dict[q_key]).group(1).strip()
    return mcq_dict

In [195]:
q_descriptor_mapping_2022 = [( "Q6_", "MOOCPlatforms_"),( "Q7_", "IntroToDSPlatform_"),( "Q12_", "ProgLanguage_"),( "Q13_", "IDE_"),( "Q14_", "HostedNB_"),( "Q15_", "VizLib_"),( "Q17_", "MLFramework_"),( "Q18_", "MLAlgo_"),( "Q19_", "CVAlgo_"),( "Q20_", "NLPAlgo_"),( "Q21_", "DownloadPreTrainedWeights_"),( "Q31_", "CloudProviderUsed_"),( "Q33_", "CloudComputeUsed_"),( "Q34_", "CloudStorageUsed_"),( "Q35_", "DBUsed_"),( "Q36_", "BIToolUsed_"),( "Q37_", "MLaaS_"),( "Q38_", "AutoMLUsed_"),( "Q39_", "MLDeploymentToolsUsed_"),( "Q40_", "MLMonitoringToolUsed_"),( "Q41_", "ResponsibleAIToolUsed_"),( "Q42_", "HardwareUsed_"),( "Q44_", "DSContentMediaConsumed_")]

In [196]:
map_cols_2022 = {
    "Q2": "Age",
    "Q3": "Gender",
    "Q4": "Country",
    "Q5": "IsStudent",
    "Q8": "HighestEducation",
    "Q9": "HasPublishedResearch",
    "Q10_1": "TheoreticalResearch",
    "Q10_2": "AppliedResearch",
    "Q10_3": "NonMLResearch",
    "Q11": "Programming Experience",
    "Q16": "MLExposure",
    "Q22": "MLReposUsed",
    "Q23": "CurrentTitle",
    "Q24": "Industry",
    "Q25": "CompanySize",
    "Q26": "DSTeamSize",
    "Q27": "IsMLUsedAtWork",
    "Q29": "AnnualComp(USD)",
    "Q30": "InvestmentInML(USD)",
    "Q32": "BestCloudProvider",
    "Q43": "TPUUsageFrequency"
}
mcq_columns = []
for q,d in q_descriptor_mapping_2022:
    q_d_mapping = extract_mcq_questions(data_dict_2022, q, d)
    map_cols_2022 = map_cols_2022 | q_d_mapping
    mcq_columns.extend(list(q_d_mapping.values()))

In [184]:
map_cols

{'Q2': 'Age',
 'Q3': 'Gender',
 'Q4': 'Country',
 'Q5': 'IsStudent',
 'Q8': 'HighestEducation',
 'Q9': 'HasPublishedResearch',
 'Q10_1': 'TheoreticalResearch',
 'Q10_2': 'AppliedResearch',
 'Q10_3': 'NonMLResearch',
 'Q11': 'Programming Experience',
 'Q16': 'MLExposure',
 'Q22': 'MLReposUsed',
 'Q23': 'CurrentTitle',
 'Q24': 'Industry',
 'Q25': 'CompanySize',
 'Q26': 'DSTeamSize',
 'Q27': 'IsMLUsedAtWork',
 'Q29': 'AnnualComp(USD)',
 'Q30': 'InvestmentInML(USD)',
 'Q32': 'BestCloudProvider',
 'Q43': 'TPUUsageFrequency',
 'Q6_1': 'MOOCPlatforms_Coursera',
 'Q6_2': 'MOOCPlatforms_edX',
 'Q6_3': 'MOOCPlatforms_Kaggle Learn Courses',
 'Q6_4': 'MOOCPlatforms_DataCamp',
 'Q6_5': 'MOOCPlatforms_Fast.ai',
 'Q6_6': 'MOOCPlatforms_Udacity',
 'Q6_7': 'MOOCPlatforms_Udemy',
 'Q6_8': 'MOOCPlatforms_LinkedIn Learning',
 'Q6_9': 'MOOCPlatforms_Cloud-certification programs (direct from AWS, Azure, GCP, or similar)',
 'Q6_10': 'MOOCPlatforms_University Courses (resulting in a university degree)',
 'Q6_11': 'MOOCPlatforms_None',
 'Q6_12': 'MOOCPlatforms_Other',
 'Q7_1': 'IntroToDSPlatform_University courses',
 'Q7_2': 'IntroToDSPlatform_Online courses (Coursera, EdX, etc)',
 'Q7_3': 'IntroToDSPlatform_Social media platforms (Reddit, Twitter, etc)',
 'Q7_4': 'IntroToDSPlatform_Video platforms (YouTube, Twitch, etc)',
 'Q7_5': 'IntroToDSPlatform_Kaggle (notebooks, competitions, etc)',
 'Q7_6': 'IntroToDSPlatform_None / I do not study data science',
 'Q7_7': 'IntroToDSPlatform_Other',
 'Q12_1': 'ProgLanguage_Python',
 'Q12_2': 'ProgLanguage_R',
 'Q12_3': 'ProgLanguage_SQL',
 'Q12_4': 'ProgLanguage_C',
 'Q12_5': 'ProgLanguage_C#',
 'Q12_6': 'ProgLanguage_C++',
 'Q12_7': 'ProgLanguage_Java',
 'Q12_8': 'ProgLanguage_Javascript',
 'Q12_9': 'ProgLanguage_Bash',
 'Q12_10': 'ProgLanguage_PHP',
 'Q12_11': 'ProgLanguage_MATLAB',
 'Q12_12': 'ProgLanguage_Julia',
 'Q12_13': 'ProgLanguage_Go',
 'Q12_14': 'ProgLanguage_None',
 'Q12_15': 'ProgLanguage_Other',
 'Q13_1': 'IDE_JupyterLab',
 'Q13_2': 'IDE_RStudio',
 'Q13_3': 'IDE_Visual Studio',
 'Q13_4': 'IDE_Visual Studio Code (VSCode)',
 'Q13_5': 'IDE_PyCharm',
 'Q13_6': 'IDE_Spyder',
 'Q13_7': 'IDE_Notepad++',
 'Q13_8': 'IDE_Sublime Text',
 'Q13_9': 'IDE_Vim / Emacs',
 'Q13_10': 'IDE_MATLAB',
 'Q13_11': 'IDE_Jupyter Notebook',
 'Q13_12': 'IDE_IntelliJ',
 'Q13_13': 'IDE_None',
 'Q13_14': 'IDE_Other',
 'Q14_1': 'HostedNB_Kaggle Notebooks',
 'Q14_2': 'HostedNB_Colab Notebooks',
 'Q14_3': 'HostedNB_Azure Notebooks',
 'Q14_4': 'HostedNB_Code Ocean',
 'Q14_5': 'HostedNB_IBM Watson Studio',
 'Q14_6': 'HostedNB_Amazon Sagemaker Studio',
 'Q14_7': 'HostedNB_Amazon Sagemaker Studio Lab',
 'Q14_8': 'HostedNB_Amazon EMR Notebooks',
 'Q14_9': 'HostedNB_Google Cloud Vertex AI Workbench',
 'Q14_10': 'HostedNB_Hex Workspaces',
 'Q14_11': 'HostedNB_Noteable Notebooks',
 'Q14_12': 'HostedNB_Databricks Collaborative Notebooks',
 'Q14_13': 'HostedNB_Deepnote Notebooks',
 'Q14_14': 'HostedNB_Gradient Notebooks',
 'Q14_15': 'HostedNB_None',
 'Q14_16': 'HostedNB_Other',
 'Q15_1': 'VizLib_Matplotlib',
 'Q15_2': 'VizLib_Seaborn',
 'Q15_3': 'VizLib_Plotly / Plotly Express',
 'Q15_4': 'VizLib_Ggplot / ggplot2',
 'Q15_5': 'VizLib_Shiny',
 'Q15_6': 'VizLib_D3 js',
 'Q15_7': 'VizLib_Altair',
 'Q15_8': 'VizLib_Bokeh',
 'Q15_9': 'VizLib_Geoplotlib',
 'Q15_10': 'VizLib_Leaflet / Folium',
 'Q15_11': 'VizLib_Pygal',
 'Q15_12': 'VizLib_Dygraphs',
 'Q15_13': 'VizLib_Highcharter',
 'Q15_14': 'VizLib_None',
 'Q15_15': 'VizLib_Other',
 'Q17_1': 'MLFramework_Scikit-learn',
 'Q17_2': 'MLFramework_TensorFlow',
 'Q17_3': 'MLFramework_Keras',
 'Q17_4': 'MLFramework_PyTorch',
 'Q17_5': 'MLFramework_Fast.ai',
 'Q17_6': 'MLFramework_Xgboost',
 'Q17_7': 'MLFramework_LightGBM',
 'Q17_8': 'MLFramework_CatBoost',
 'Q17_9': 'MLFramework_Caret',
 'Q17_10': 'MLFramework_Tidymodels',
 'Q17_11': 'MLFramework_JAX',
 'Q17_12': 'MLFramework_PyTorch Lightning',
 'Q17_13': 'MLFramework_Huggingface',
 'Q17_14': 'MLFramework_None',
 'Q17_15': 'MLFramework_Other',
 'Q18_1': 'MLAlgo_Linear or Logistic Regression',
 'Q18_2': 'MLAlgo_Decision Trees or Random Forests',
 'Q18_3': 'MLAlgo_Gradient Boosting Machines (xgboost, lightgbm, etc)',
 'Q18_4': 'MLAlgo_Bayesian Approaches',
 'Q18_5': 'MLAlgo_Evolutionary Approaches',
 'Q18_6': 'MLAlgo_Dense Neural Networks (MLPs, etc)',
 'Q18_7': 'MLAlgo_Convolutional Neural Networks',
 'Q18_8': 'MLAlgo_Generative Adversarial Networks',
 'Q18_9': 'MLAlgo_Recurrent Neural Networks',
 'Q18_10': 'MLAlgo_Transformer Networks (BERT, gpt-3, etc)',
 'Q18_11': 'MLAlgo_Autoencoder Networks (DAE, VAE, etc)',
 'Q18_12': 'MLAlgo_Graph Neural Networks',
 'Q18_13': 'MLAlgo_None',
 'Q18_14': 'MLAlgo_Other',
 'Q19_1': 'CVAlgo_General purpose image/video tools (PIL, cv2, skimage, etc)',
 'Q19_2': 'CVAlgo_Image segmentation methods (U-Net, Mask R-CNN, etc)',
 'Q19_3': 'CVAlgo_Object detection methods (YOLOv6, RetinaNet, etc)',
 'Q19_4': 'CVAlgo_Image classification and other general purpose networks (VGG, Inception, ResNet, ResNeXt, NASNet, EfficientNet, etc)',
 'Q19_5': 'CVAlgo_Generative Networks (GAN, VAE, etc)',
 'Q19_6': 'CVAlgo_Vision transformer networks (ViT, DeiT, BiT, BEiT, Swin, etc)',
 'Q19_7': 'CVAlgo_None',
 'Q19_8': 'CVAlgo_Other',
 'Q20_1': 'NLPAlgo_Word embeddings/vectors (GLoVe, fastText, word2vec)',
 'Q20_2': 'NLPAlgo_Encoder-decoder models (seq2seq, vanilla transformers)',
 'Q20_3': 'NLPAlgo_Contextualized embeddings (ELMo, CoVe)',
 'Q20_4': 'NLPAlgo_Transformer language models (GPT-3, BERT, XLnet, etc)',
 'Q20_5': 'NLPAlgo_None',
 'Q20_6': 'NLPAlgo_Other',
 'Q21_1': 'DownloadPreTrainedWeights_TensorFlow Hub',
 'Q21_2': 'DownloadPreTrainedWeights_PyTorch Hub',
 'Q21_3': 'DownloadPreTrainedWeights_Huggingface Models',
 'Q21_4': 'DownloadPreTrainedWeights_Timm',
 'Q21_5': 'DownloadPreTrainedWeights_Jumpstart',
 'Q21_6': 'DownloadPreTrainedWeights_ONNX models',
 'Q21_7': 'DownloadPreTrainedWeights_NVIDIA NGC models',
 'Q21_8': 'DownloadPreTrainedWeights_Kaggle datasets',
 'Q21_9': 'DownloadPreTrainedWeights_No, I do not download pre-trained model weights on a regular basis',
 'Q21_10': 'DownloadPreTrainedWeights_Other storage services (i.e. google drive)',
 'Q31_1': 'CloudProviderUsed_Amazon Web Services (AWS)',
 'Q31_2': 'CloudProviderUsed_Microsoft Azure',
 'Q31_3': 'CloudProviderUsed_Google Cloud Platform (GCP)',
 'Q31_4': 'CloudProviderUsed_IBM Cloud / Red Hat',
 'Q31_5': 'CloudProviderUsed_Oracle Cloud',
 'Q31_6': 'CloudProviderUsed_SAP Cloud',
 'Q31_7': 'CloudProviderUsed_VMware Cloud',
 'Q31_8': 'CloudProviderUsed_Alibaba Cloud',
 'Q31_9': 'CloudProviderUsed_Tencent Cloud',
 'Q31_10': 'CloudProviderUsed_Huawei Cloud',
 'Q31_11': 'CloudProviderUsed_None',
 'Q31_12': 'CloudProviderUsed_Other',
 'Q33_1': 'CloudComputeUsed_Amazon Elastic Compute Cloud (EC2)',
 'Q33_2': 'CloudComputeUsed_Microsoft Azure Virtual Machines',
 'Q33_3': 'CloudComputeUsed_Google Cloud Compute Engine',
 'Q33_4': 'CloudComputeUsed_No / None',
 'Q33_5': 'CloudComputeUsed_Other',
 'Q34_1': 'CloudStorageUsed_Microsoft Azure Blob Storage',
 'Q34_2': 'CloudStorageUsed_Microsoft Azure Files',
 'Q34_3': 'CloudStorageUsed_Amazon Simple Storage Service (S3)',
 'Q34_4': 'CloudStorageUsed_Amazon Elastic File System (EFS)',
 'Q34_5': 'CloudStorageUsed_Google Cloud Storage (GCS)',
 'Q34_6': 'CloudStorageUsed_Google Cloud Filestore',
 'Q34_7': 'CloudStorageUsed_No / None',
 'Q34_8': 'CloudStorageUsed_Other',
 'Q35_1': 'DBUsed_MySQL',
 'Q35_2': 'DBUsed_PostgreSQL',
 'Q35_3': 'DBUsed_SQLite',
 'Q35_4': 'DBUsed_Oracle Database',
 'Q35_5': 'DBUsed_MongoDB',
 'Q35_6': 'DBUsed_Snowflake',
 'Q35_7': 'DBUsed_IBM Db2',
 'Q35_8': 'DBUsed_Microsoft SQL Server',
 'Q35_9': 'DBUsed_Microsoft Azure SQL Database',
 'Q35_10': 'DBUsed_Amazon Redshift',
 'Q35_11': 'DBUsed_Amazon RDS',
 'Q35_12': 'DBUsed_Amazon DynamoDB',
 'Q35_13': 'DBUsed_Google Cloud BigQuery',
 'Q35_14': 'DBUsed_Google Cloud SQL',
 'Q35_15': 'DBUsed_None',
 'Q35_16': 'DBUsed_Other',
 'Q36_1': 'BIToolUsed_Amazon QuickSight',
 'Q36_2': 'BIToolUsed_Microsoft Power BI',
 'Q36_3': 'BIToolUsed_Google Data Studio',
 'Q36_4': 'BIToolUsed_Looker',
 'Q36_5': 'BIToolUsed_Tableau',
 'Q36_6': 'BIToolUsed_Qlik Sense',
 'Q36_7': 'BIToolUsed_Domo',
 'Q36_8': 'BIToolUsed_TIBCO Spotfire',
 'Q36_9': 'BIToolUsed_Alteryx',
 'Q36_10': 'BIToolUsed_Sisense',
 'Q36_11': 'BIToolUsed_SAP Analytics Cloud',
 'Q36_12': 'BIToolUsed_Microsoft Azure Synapse',
 'Q36_13': 'BIToolUsed_Thoughtspot',
 'Q36_14': 'BIToolUsed_None',
 'Q36_15': 'BIToolUsed_Other',
 'Q37_1': 'MLaaS_Amazon SageMaker',
 'Q37_2': 'MLaaS_Azure Machine Learning Studio',
 'Q37_3': 'MLaaS_Google Cloud Vertex AI',
 'Q37_4': 'MLaaS_DataRobot',
 'Q37_5': 'MLaaS_Databricks',
 'Q37_6': 'MLaaS_Dataiku',
 'Q37_7': 'MLaaS_Alteryx',
 'Q37_8': 'MLaaS_Rapidminer',
 'Q37_9': 'MLaaS_C3.ai',
 'Q37_10': 'MLaaS_Domino Data Lab',
 'Q37_11': 'MLaaS_H2O AI Cloud',
 'Q37_12': 'MLaaS_No / None',
 'Q37_13': 'MLaaS_Other',
 'Q38_1': 'AutoMLUsed_Google Cloud AutoML',
 'Q38_2': 'AutoMLUsed_H2O Driverless AI',
 'Q38_3': 'AutoMLUsed_Databricks AutoML',
 'Q38_4': 'AutoMLUsed_DataRobot AutoML',
 'Q38_5': 'AutoMLUsed_Amazon Sagemaker Autopilot',
 'Q38_6': 'AutoMLUsed_Azure Automated Machine Learning',
 'Q38_7': 'AutoMLUsed_No / None',
 'Q38_8': 'AutoMLUsed_Other',
 'Q39_1': 'MLDeploymentToolsUsed_TensorFlow Extended (TFX)',
 'Q39_2': 'MLDeploymentToolsUsed_TorchServe',
 'Q39_3': 'MLDeploymentToolsUsed_ONNX Runtime',
 'Q39_4': 'MLDeploymentToolsUsed_Triton Inference Server',
 'Q39_5': 'MLDeploymentToolsUsed_OpenVINO Model Server',
 'Q39_6': 'MLDeploymentToolsUsed_KServe',
 'Q39_7': 'MLDeploymentToolsUsed_BentoML',
 'Q39_8': 'MLDeploymentToolsUsed_Multi Model Server (MMS)',
 'Q39_9': 'MLDeploymentToolsUsed_Seldon Core',
 'Q39_10': 'MLDeploymentToolsUsed_MLflow',
 'Q39_11': 'MLDeploymentToolsUsed_None',
 'Q39_12': 'MLDeploymentToolsUsed_Other',
 'Q40_1': 'MLMonitoringToolUsed_Neptune.ai',
 'Q40_2': 'MLMonitoringToolUsed_Weights & Biases',
 'Q40_3': 'MLMonitoringToolUsed_Comet.ml',
 'Q40_4': 'MLMonitoringToolUsed_TensorBoard',
 'Q40_5': 'MLMonitoringToolUsed_Guild.ai',
 'Q40_6': 'MLMonitoringToolUsed_ClearML',
 'Q40_7': 'MLMonitoringToolUsed_MLflow',
 'Q40_8': 'MLMonitoringToolUsed_Aporia',
 'Q40_9': 'MLMonitoringToolUsed_Evidently AI',
 'Q40_10': 'MLMonitoringToolUsed_Arize',
 'Q40_11': 'MLMonitoringToolUsed_WhyLabs',
 'Q40_12': 'MLMonitoringToolUsed_Fiddler',
 'Q40_13': 'MLMonitoringToolUsed_DVC',
 'Q40_14': 'MLMonitoringToolUsed_No / None',
 'Q40_15': 'MLMonitoringToolUsed_Other',
 'Q41_1': 'ResponsibleAIToolUsed_Google Responsible AI Toolkit (LIT, What-if, Fairness Indicator, etc)',
 'Q41_2': 'ResponsibleAIToolUsed_Microsoft Responsible AI Resources (Fairlearn, Counterfit, InterpretML, etc)',
 'Q41_3': 'ResponsibleAIToolUsed_IBM AI Ethics tools (AI Fairness 360, Adversarial Robustness Toolbox, etc',
 'Q41_4': 'ResponsibleAIToolUsed_Amazon AI Ethics Tools (Clarify, A2I, etc)',
 'Q41_5': 'ResponsibleAIToolUsed_The LinkedIn Fairness Toolkit (LiFT)',
 'Q41_6': 'ResponsibleAIToolUsed_Audit-AI',
 'Q41_7': 'ResponsibleAIToolUsed_Aequitas',
 'Q41_8': 'ResponsibleAIToolUsed_None',
 'Q41_9': 'ResponsibleAIToolUsed_Other',
 'Q42_1': 'HardwareUsed_GPUs',
 'Q42_2': 'HardwareUsed_TPUs',
 'Q42_3': 'HardwareUsed_IPUs',
 'Q42_4': 'HardwareUsed_RDUs',
 'Q42_5': 'HardwareUsed_WSEs',
 'Q42_6': 'HardwareUsed_Trainium Chips',
 'Q42_7': 'HardwareUsed_Inferentia Chips',
 'Q42_8': 'HardwareUsed_None',
 'Q42_9': 'HardwareUsed_Other',
 'Q44_1': 'DSContentMediaConsumed_Twitter (data science influencers)',
 'Q44_2': "DSContentMediaConsumed_Email newsletters (Data Elixir, O'Reilly Data & AI, etc)",
 'Q44_3': 'DSContentMediaConsumed_Reddit (r/machinelearning, etc)',
 'Q44_4': 'DSContentMediaConsumed_Kaggle (notebooks, forums, etc)',
 'Q44_5': 'DSContentMediaConsumed_Course Forums (forums.fast.ai, Coursera forums, etc)',
 'Q44_6': 'DSContentMediaConsumed_YouTube (Kaggle YouTube, Cloud AI Adventures, etc)',
 'Q44_7': 'DSContentMediaConsumed_Podcasts (Chai Time Data Science, O’Reilly Data Show, etc)',
 'Q44_8': 'DSContentMediaConsumed_Blogs (Towards Data Science, Analytics Vidhya, etc)',
 'Q44_9': 'DSContentMediaConsumed_Journal Publications (peer-reviewed journals, conference proceedings, etc)',
 'Q44_10': 'DSContentMediaConsumed_Slack Communities (ods.ai, kagglenoobs, etc)',
 'Q44_11': 'DSContentMediaConsumed_None',
 'Q44_12': 'DSContentMediaConsumed_Other'}

In [190]:
df_2022 = df_2022.rename(map_cols, axis=1)
df_2022 = df_2022.loc[1:,:]

In [191]:
for mcq_column in mcq_columns:
    df_2022.loc[~df_2022[mcq_column].isin([np.nan]), mcq_column] = 1
    df_2022.loc[df_2022[mcq_column].isin([np.nan]), mcq_column] = 0

In [224]:
df_2021 = pd.read_csv("data/kaggle_survey_2021_responses.csv")

/var/folders/6v/12r4qnjx54zgmfy66mv7j0rr0000gn/T/ipykernel_28764/340828643.py:1: DtypeWarning: Columns (0,195,201,285,286,287,288,289,290,291,292) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv("kaggle_survey_2021_responses.csv")

In [225]:
data_dict_2021 = df_2021.loc[0,:].to_dict()

In [226]:
q_descriptor_mapping_2021 = [( "40_", "MOOCPlatforms_"),( "Q7_", "ProgLanguage_"),( "Q9_", "IDE_"),( "Q10_", "HostedNB_"),( "Q14_", "VizLib_"),( "Q16_", "MLFramework_"),( "Q17_", "MLAlgo_"),( "Q18_", "CVAlgo_"),( "Q19_", "NLPAlgo_"),( "Q27_A_", "CloudProviderUsed_"),( "Q29_A_", "CloudComputeUsed_"),( "Q30_A_", "CloudStorageUsed_"),( "Q32_A_", "DBUsed_"),( "Q34_A_", "BIToolUsed_"),( "Q31_A_", "MLaaS_"),( "Q37_A_", "AutoMLUsed_"),( "Q36_A_", "AutoMLFrameworksUsed_"),( "Q39_", "PublishDSMedium_"),( "Q38_A_", "MLMonitoringToolUsed_"),( "Q12_", "HardwareUsed_"),( "Q42_", "DSContentMediaConsumed_")]

In [227]:
map_cols_2021 = {
    "Time from Start to Finish (seconds)": "Duration (in seconds)",
    "Q1": "Age",
    "Q2": "Gender",
    "Q3": "Country",
#     "Q5": "IsStudent",
    "Q4": "HighestEducation",
#     "Q9": "HasPublishedResearch",
#     "Q10_1": "TheoreticalResearch",
#     "Q10_2": "AppliedResearch",
#     "Q10_3": "NonMLResearch",
    "Q6": "Programming Experience",
    "Q15": "MLExposure",
#     "Q22": "MLReposUsed",
    "Q5": "CurrentTitle",
    "Q20": "Industry",
    "Q21": "CompanySize",
    "Q22": "DSTeamSize",
    "Q23": "IsMLUsedAtWork",
    "Q25": "AnnualComp(USD)",
    "Q26": "InvestmentInML(USD)",
    "Q28": "BestCloudProvider",
    "Q13": "TPUUsageFrequency",
    "Q33": "MostUsedBigDataProduct",
    "Q35": "MostUsedBITool"
}
mcq_columns = []
for q,d in q_descriptor_mapping_2021:
    q_d_mapping = extract_mcq_questions(data_dict_2021, q, d)
    map_cols_2021 = map_cols_2021 | q_d_mapping
    mcq_columns.extend(list(q_d_mapping.values()))

In [228]:
df_2021 = df_2021.rename(map_cols_2021, axis=1)

In [229]:
df_2021

,Duration (in seconds),Age,Gender,Country,HighestEducation,CurrentTitle,Programming Experience,ProgLanguage_Python,ProgLanguage_R,ProgLanguage_SQL,...,Q38_B_Part_3,Q38_B_Part_4,Q38_B_Part_5,Q38_B_Part_6,Q38_B_Part_7,Q38_B_Part_8,Q38_B_Part_9,Q38_B_Part_10,Q38_B_Part_11,Q38_B_OTHER
0,Duration (in seconds),What is your age (# years)?,What is your gender? - Selected Choice,In which country do you currently reside?,What is the highest level of formal education ...,Select the title most similar to your current ...,For how many years have you been writing code ...,What programming languages do you use on a reg...,What programming languages do you use on a reg...,What programming languages do you use on a reg...,...,"In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor...","In the next 2 years, do you hope to become mor..."
1,910,50-54,Man,India,Bachelor’s degree,Other,5-10 years,Python,R,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,784,50-54,Man,Indonesia,Master’s degree,Program/Project Manager,20+ years,NaN,NaN,SQL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
3,924,22-24,Man,Pakistan,Master’s degree,Software Engineer,1-3 years,Python,NaN,NaN,...,NaN,NaN,TensorBoard,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,575,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Python,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25969,1756,30-34,Man,Egypt,Bachelor’s degree,Data Analyst,1-3 years,Python,NaN,SQL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,253,22-24,Man,China,Master’s degree,Student,1-3 years,Python,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,494,50-54,Man,Sweden,Doctoral degree,Research Scientist,I have never written code,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
25972,277,45-49,Man,United States of America,Master’s degree,Data Scientist,5-10 years,Python,NaN,SQL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,255,18-21,Man,India,Bachelor’s degree,Business Analyst,I have never written code,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN

In [230]:
df_2021 = df_2021.loc[1:,:]

In [231]:
for mcq_column in mcq_columns:
    df_2021.loc[~df_2021[mcq_column].isin([np.nan]), mcq_column] = 1
    df_2021.loc[df_2021[mcq_column].isin([np.nan]), mcq_column] = 0

/var/folders/6v/12r4qnjx54zgmfy66mv7j0rr0000gn/T/ipykernel_28764/2888068137.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021.loc[~df_2021[mcq_column].isin([np.nan]), mcq_column] = 1
/var/folders/6v/12r4qnjx54zgmfy66mv7j0rr0000gn/T/ipykernel_28764/2888068137.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021.loc[df_2021[mcq_column].isin([np.nan]), mcq_column] = 0

In [232]:
df_2021.loc[df_2021["CurrentTitle"]=="Student","IsStudent"] = "Yes"
df_2021.loc[df_2021["IsStudent"].isna(), "IsStudent"] = "No"

/var/folders/6v/12r4qnjx54zgmfy66mv7j0rr0000gn/T/ipykernel_28764/1128806736.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021.loc[df_2021["CurrentTitle"]=="Student","IsStudent"] = "Yes"

In [233]:
df_2022["SurveyYear"] = 2022
df_2021["SurveyYear"] = 2021

/var/folders/6v/12r4qnjx54zgmfy66mv7j0rr0000gn/T/ipykernel_28764/3545890937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021["SurveyYear"] = 2021

In [234]:
data = pd.concat([df_2022, df_2021])

In [235]:
def categorize_education(education:str) -> str:
    """Assigns more general categories to education levels.
    """
    if education in [
        "No formal education past high school", 
        "Some college/university study without earning a bachelor’s degree"
    ]:
        return "Lower than Bachelor"
    
    if education == "Bachelor’s degree":
        return "Bachelor"
    
    if education == "Master’s degree":
        return "Master"
    
    if education in ["Doctoral degree", "Professional doctorate"]:
        return "Higher than Master"
    
    return "Other"


def assign_label(service:str):
    """It returns the company name to which the product belongs. 
    It takes care only of the 3 big techs: Google, Microsoft, Amazon.
    """
    
    if "google" in service.lower():
        return "Google"
    
    if "aws" in service.lower() or "amazon" in service.lower():
        return "Amazon"
    
    if "azure" in service.lower() or "microsoft" in service.lower():
        return "Microsoft"
    
    if "ibm" in service.lower():
        return "IBM"

    return "Other"

In [236]:
data["HighestEducation"] = data["HighestEducation"].apply(lambda x: categorize_education(x))

In [237]:
data

,Duration (in seconds),Age,Gender,Country,IsStudent,MOOCPlatforms_Coursera,MOOCPlatforms_edX,MOOCPlatforms_Kaggle Learn Courses,MOOCPlatforms_DataCamp,MOOCPlatforms_Fast.ai,...,Q38_B_Part_3,Q38_B_Part_4,Q38_B_Part_5,Q38_B_Part_6,Q38_B_Part_7,Q38_B_Part_8,Q38_B_Part_9,Q38_B_Part_10,Q38_B_Part_11,Q38_B_OTHER
1,121,30-34,Man,India,No,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,462,30-34,Man,Algeria,No,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,293,18-21,Man,Egypt,Yes,1,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,851,55-59,Man,France,No,1,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,232,45-49,Man,India,Yes,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25969,1756,30-34,Man,Egypt,No,1,0,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,253,22-24,Man,China,Yes,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,494,50-54,Man,Sweden,No,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
25972,277,45-49,Man,United States of America,No,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,255,18-21,Man,India,No,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN

In [238]:
data.to_csv("data/KaggleSurveyData_2021+2022.csv")